name: main
on:
  push:
    branches:
      - main
jobs:
  build-hs789:
    runs-on: ubuntu-latest
    env:
      PRE_RELEASE_ID: 64125785
      PRE_RELEASE_TAG: vmain
      ZIP_NAME: hs-b787-9-${{ github.ref_name }}.zip
      BUILD_DIR_NAME: main
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Delete old GitHub Pre-Release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.PRE_RELEASE_TAG }}
          assets: "*"
          fail-if-no-assets: false
          fail-if-no-release: false
      - name: Install required dependencies
        run: |
            npm i --save-dev
      - name: Copy Sources
        run: |
            npm run prep-hs789:copy-base-package-linux
            npm run build-hs789:copy-model-linux
      - name: Finalize built package
        run: |
            npm run build-hs789:metadata
            npm run build-hs789:manifest
      - name: Generate HorizonSim-789 ZIP file
        run: |
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./horizonsim-789/build/
          zip -r ../../${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME }} ./horizonsim-aircraft-787-9/
          cd ../../
      - name: Upload to Cloudflare CDN
        env:
          CLOUDFLARE_BUCKET_PASSWORD: ${{ secrets.CLOUDFLARE_BUCKET_PASSWORD }}
          CDN_BUCKET_DESTINATION: addons/horizonsim-789/development
        run: |
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./horizonsim-789/build/build-modules
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDS_B789 }}
          filename: ./${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME}}
          folderId: ${{ secrets.GDRIVEFOLDERID }}
          overwrite: "true" # optional boolean
