name: main
on:
  push:
    branches:
      - main
jobs:
  build-hs789:
    runs-on: ubuntu-latest
    env:
      PRE_RELEASE_ID: 64125785
      PRE_RELEASE_TAG: vmain
      ZIP_NAME: hs-b787-9-${{ github.ref_name }}.zip
      BUILD_DIR_NAME: main
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Delete old GitHub Pre-Release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.PRE_RELEASE_TAG }}
          assets: "*"
          fail-if-no-assets: false
          fail-if-no-release: false
      - name: Setup Package
        run:  |
            ./scripts/dev-env/run.sh ./scripts/setup.sh
      - name: Copy Sources
        run: |
            ./scripts/dev-env/run.sh ./scripts/copy_hs789.sh
      - name: Build A21NHS Package
        run: |
              ./scripts/dev-env/run.sh ./scripts/build_hs789.sh --no-tty -j 4
      - name: Generate HorizonSim-789 ZIP file
        run: |
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./build-a321neo/out/
          zip -r ../../${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME }} ./lvfr-horizonsim-airbus-a321-neo/
          cd ../../
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDS_B789 }}
          filename: ./${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME}}
          folderId: ${{ secrets.GDRIVEFOLDERID }}
          overwrite: "true" # optional boolean
